"""create professor table

Revision ID: 0ca95b863cc7
Revises: ce4e2b6075b2
Create Date: 2023-03-12 15:18:53.662910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca95b863cc7'
down_revision = 'ce4e2b6075b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
