"""add unique for user id in Professor table

Revision ID: 42edc71a1b64
Revises: 1d2baa7a495c
Create Date: 2023-03-12 16:15:00.279482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42edc71a1b64'
down_revision = '1d2baa7a495c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'professors', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'professors', type_='unique')
    # ### end Alembic commands ###
