"""create student table

Revision ID: 85b86cdc4910
Revises: 0ca95b863cc7
Create Date: 2023-03-12 15:22:02.956448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b86cdc4910'
down_revision = '0ca95b863cc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
