"""create administrator  table

Revision ID: cffa4bef462e
Revises: 85b86cdc4910
Create Date: 2023-03-12 15:25:48.317081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cffa4bef462e'
down_revision = '85b86cdc4910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
